### PR TITLE
fix: typos in documentation files

### PR DESCRIPTION
**Pull request by leopardracer**
This pull request contains changes to improve clarity, correctness and structure.

**Description correction:**
Corrected `convertion` to `conversion`

Please review the changes and let me know if any additional changes are needed.

### CODE REVIEW

**Comment by leopardracer** [comment]
@skaunov Hi! Apologies for the inconvenience. I just wanted to check if there’s anything I can improve in my pull request. Please feel free to ask any questions or let me know if any changes are needed to meet the project's merge requirements. I’m happy to make adjustments!

**Comment by skaunov** [comment]
No problem! I hash-tagged that for quick orientation to a relevant part, hence I bet there's more occurrences of that. Could you change them together in this contribution?

**Comment by leopardracer** [comment]
> No problem! I hash-tagged that for quick orientation to a relevant part, hence I bet there's more occurrences of that. Could you change them together in this contribution?

Yes, of course! What exactly needs to be changed?

**Comment by skaunov** [comment]
other occurrences of "#convertion"

On 2024-12-03 16:34, leopardracer wrote:

>> No problem! I hash-tagged that for quick orientation to a relevant 
>> part, hence I bet there's more occurrences of that. Could you change 
>> them together in this contribution?
> 
> Yes, of course! What exactly needs to be changed?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/plume-sig/zk-nullifier-sig/pull/119#issuecomment-2514898862
[2]

**Comment by Divide-By-0** [comment]
@leopardracer please stop submitting typo correction PRs and wasting maintainer time.

**Pull request closed without merging**
