### PR TITLE
22

### PR DESCRIPTION
**Pull request by skaunov**
tests weren't touched on purpose to raise additional awareness of those who will be modifying them to recheck implementations against each other

### CODE REVIEW

**Comment by skaunov** [comment]
I should notice [another](https://github.com/plume-sig/zk-nullifier-sig/commit/251fba690295d23fd5b14c59e4c03edb263122c0#commitcomment-130098317) confusing naming: `s` and `sk`. =(

**Comment by Divide-By-0** [comment]
No one's using tests yet, feel free to edit those. S isn't ideal I agree, open to anything else.

**Comment by Divide-By-0** [comment]
For circom, the code is way cleaner if you do this: https://github.com/plume-sig/zk-nullifier-sig/pull/48

Can you merge in that PR first, compile the circuits to make sure they work? It will make circom easier to read and maintain.

**Comment by skaunov** [comment]
> Can you merge in that PR first, compile the circuits to make sure they work? It will make circom easier to read and maintain.

Ok, am running test suite rn. Merging amount is unexpected. :exploding_head:

**Comment by skaunov** [comment]
> No one's using tests yet, feel free to edit those. S isn't ideal I agree, open to anything else.

I meant that I think it's actually good to preserve reasonable cognitive load in tests. I updated parts which were too confusing; though they're relatively rough and unpolished for good.

I'll think further about "S" though you can see absence of suggestions on my side. X)

**Comment by skaunov** [comment]
To be merged via #66 due to merging conflict.

**Pull request closed without merging**
