### PR TITLE
Fix array signals

### LINKED ISSUE #19: Can use circom 2.1 feature for array constraints
Circom 2.1 allows using `<==` operator for signal arrays ([documentation](https://docs.circom.io/circom-language/anonymous-components-and-tuples/#the-use-of-for-signal-arrays)). You can avoid writing loops just to assign inputs to a component.

For example:
```diff
-for (var i = 0; i < k; i++) {
-    g_pow_s.privkey[i] <== s[i];
-}
+g_pow_s.privkey <== s
```

### PR DESCRIPTION
**Pull request by RajeshRk18**
Fixes #19

### CODE REVIEW

**Comment by RajeshRk18** [comment]
@Divide-By-0 
To run tests, I need to run `npm cache clean --force` and then run tests. Idk whats the issue. But, the error seems to be like secp256k1_hash_to_curve_circom lib is corrupted. Checksum failed

**Comment by Divide-By-0** [comment]
We just patched the lib, see the last commit. You'll need to delete yarn lock and remake.  https://github.com/geometryresearch/secp256k1_hash_to_curve

**Comment by Divide-By-0** [comment]
Hey -- we have no idea if the changes you made are correct unless we have some test we can use to evaluate the circom circuit. Can you add a circom test via circom-tester to the CI to verify that it's still constrained correctly?

**Comment by RajeshRk18** [comment]
> Hey -- we have no idea if the changes you made are correct unless we have some test we can use to evaluate the circom circuit. Can you add a circom test via circom-tester to the CI to verify that it's still constrained correctly?

Create an issue to add circom tester to the CI. I will try.

**Comment by RajeshRk18** [comment]
I tried running tests. Most of the time, it gets killed, maybe oom issue idk. 
Can you help me with this?

**Comment by Divide-By-0** [comment]
Yes. Set max workers to 2: https://github.com/zkemail/zk-email-verify/pull/104

**Comment by Divide-By-0** [comment]
You can also use circleci or just have the witness generation be the test.

**Comment by skaunov** [comment]
I suppose @Divide-By-0 [reviewed](https://github.com/plume-sig/zk-nullifier-sig/pull/64#issuecomment-1772052758) the code, since I only ran the test suite (it's green). And now will be merging, maybe with squashing.

**Pull request closed without merging**
