### PR TITLE
Solution for #23

### PR DESCRIPTION
**Pull request by skaunov**
# proposed commit message for squashing merge
`c` switched to be hash in the crates

`c` conversion to number / field element moved to consuming functions
more like it's in <./javascript> now

### CODE REVIEW

**Comment by Divide-By-0** [comment]
Hey sorry we are depreciating sha512, can you switch this to sha256? I saw it in the comments but c definitely won't be the same across implementations if some are sha512.

**Comment by skaunov** [comment]
Okay... Will add a commit.
Just didn't want to mix root cause of #23 with SHA-2 variant migration. X)

**Comment by Divide-By-0** [comment]
Oh, got it. Makes sense then. Will just note then that c itself is still inconsistent. I edited that issue title, can merge this!

**Comment by Divide-By-0** [comment]
Well one problem on the tests, it fails since 

npm ERR! sha512-X7RxH19+hScc5pluCyS+f6P9EcZtJm189LgBqDOI018sP+SGmkFmtUk+Z+km5Go9qYRSLsaU84k/gUlRZGYWVA== integrity checksum failed when using sha512: wanted sha512-X7RxH19+hScc5pluCyS+f6P9EcZtJm189LgBqDOI018sP+SGmkFmtUk+Z+km5Go9qYRSLsaU84k/gUlRZGYWVA== but got sha512-rvEAEILDvmfdBLWtlrU18jajpnRmJKARoaHlcWRYen9QSJvmhTZsGtyLKIetUCjX2lzggy3/HdLJyZpi/v0VuQ==. (143867 bytes)

**Comment by skaunov** [comment]
> Well one problem on the tests, it fails since
> 
> npm ERR! sha512-X7RxH19+hScc5pluCyS+f6P9EcZtJm189LgBqDOI018sP+SGmkFmtUk+Z+km5Go9qYRSLsaU84k/gUlRZGYWVA== integrity checksum failed when using sha512: wanted sha512-X7RxH19+hScc5pluCyS+f6P9EcZtJm189LgBqDOI018sP+SGmkFmtUk+Z+km5Go9qYRSLsaU84k/gUlRZGYWVA== but got sha512-rvEAEILDvmfdBLWtlrU18jajpnRmJKARoaHlcWRYen9QSJvmhTZsGtyLKIetUCjX2lzggy3/HdLJyZpi/v0VuQ==. (143867 bytes)

It's the one which runs the suit in <./circuits>, to my shame I don't know how to detach it from this PR. :upside_down_face: I already updated that workflow to scope only <./javascript>. And updated passes! X)

**Pull request merged**
